### ISSUE TITLE
Exception in neuroevolution example

### ISSUE THREAD

**Issue by jordanderson** [giuse/machine_learning_workbench#1]
https://github.com/giuse/machine_learning_workbench/blob/fb2f72914aa414e71537c02c8c783c62a9c2ef8f/examples/neuroevolution.rb#L39

As written, I get an exception:
```
NoMethodError: undefined method `first' for "Numo::DFloat#shape=[1,1]\n[[0.314217]]":Numo::DFloat
```
Seems to work correctly if I do `output = NET.activate(input).to_f` instead. I'm just starting to look at this project so I may be missing something obvious.

**Comment by giuse** [comment]
I forgot to update the example after switching to Numo. Thanks for catching it, I'll fix it right away.
